'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MR_HR

    '''<summary>
    '''scriptmanager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents scriptmanager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''pnlModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlModal As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnCloseModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCloseModal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblClaim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClaim As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtClaim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClaim As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblNIPModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNIPModal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNIPModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNIPModal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblNamaModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNamaModal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNamaModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNamaModal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblDepartemenModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDepartemenModal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDepartemenModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDepartemenModal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblKategoriModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKategoriModal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtKategoriModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKategoriModal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTanggalModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTanggalModal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTanggalModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTanggalModal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblBiayaModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBiayaModal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbiayaModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbiayaModal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblKwitansi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKwitansi As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgKwitansi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgKwitansi As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblResep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResep As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgResep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgResep As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblPendukung control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPendukung As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgPendukung control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgPendukung As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''btnSetuju control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSetuju As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btntidaksetuju control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btntidaksetuju As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvRequestList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvRequestList As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gvHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvHistory As Global.System.Web.UI.WebControls.GridView
End Class
